### ISSUE TITLE
Design "pull boot" notification

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#1115]
"Pull boot"- when you pull and get booted out of the screen you were on because someone else deleted a site or project or did something else that causes you to no longer be able to see that screen. This would only happen when you’re online.

[Figma design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10659-6337&t=3e84APimNUKTGMru-1)

**Comment by CourtneyLee333** [comment]
@DerekCaelin Ready for your review.

**Comment by DerekCaelin** [comment]
In this scenario, wouldn't we use the [Synchronization error](https://landpks.terraso.org/help/synchronization-conflict/) notification? 

I think we just need to define the experience for the user if they are on a site/project screen that disappears during a pull. Perhaps they get kicked up to the site screen?

**Comment by CourtneyLee333** [comment]
@DerekCaelin My line of thinking is that the "pull boot" message is specifically for when you're kicked out of the screen you're currently on because of the pull, whether you've entered data or not. Whereas the sync conflict message displays when you aren't on the affected screen but data you entered previously can't be synced because of a change. 

But I suppose the sync conflict message could be used for both, at least until we get into more nuanced messaging down the road. So I'm fine if you want to handle it that way.

**Comment by DerekCaelin** [comment]
Ah, I see. I hadn't thought of the scenario in which the user has _not_ entered data for a site but is still booted out because the site has been moved/deleted. In that case, "Sync conflict" doesn't really cover it. It feels like we do need a different error message for this scenario. Could give more information in the pull boot error message? Like:

`[object name] is no longer available.`

But what happens if a sync conflict and a pull boot occur? What happens if:
1. a contributor adds data to a project site
2. the site gets moved/deleted by a manager
3. the contributor's client pulls while the user is on the site

We could display both errors, one after another?

**Comment by CourtneyLee333** [comment]
For MVP we decided to be super minimalist with the messaging, not getting into nuances about what actually happened (there could be so many possibilities!) I think showing two messages in a row would be annoying and confusing. Do you think "Project conflict" would cover both scenarios, generically? Then we add some more info to the help documentation to cover the additional scenario?

**Comment by DerekCaelin** [comment]
I've updated the [help text - what do you think? ](https://docs.google.com/document/d/1Mmdkhgelb_5TkDeFqM_UifHsTvl5sgsmWQTh5BtTC-0/edit?tab=t.0)

**Comment by CourtneyLee333** [comment]
I made a few edits to make it less about being offline, since these conflicts just as easily happen while online.

**Comment by DerekCaelin** [comment]
OK I think this is ready
