### ISSUE TITLE
in story maps, accept mp4 as media type

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#145]
We currently accept media files but not mp4s in story maps. We should accept mp4s as ways for people to share small videos. 

Scenario:
Joseph from a Maasai tribe in Kenya has a small video he wants to share: 

https://github.com/techmatters/terraso-product/assets/10799815/7d36fb28-1f12-43eb-beb8-8bb1138d2eee

Currently he has no way to share it. 

# Assumptions
video files will be under 10mb, which is the current file size limitation

## Acceptance criteria
- [x] accept .mp4 uploads in story maps
- [x] add .mp4 to the list of accepted media in the uploader module for story maps
- [x] Updated design - implemented
- [x] Copy edits (not needed)
- [ ] Translation to spanish

**Comment by Hanal-code** [comment]
@DerekCaelin _Re to your question--What are your thoughts on whether we should do this?_ 
I think so. During the usability study, multiple participants expressed their desires to upload a video files from their laptop. The current limitations of linking a YouTube/Vimeo video didn't meet their needs.

**Comment by DerekCaelin** [comment]
Thanks @Hanal-code! I notice you labeled this as design size "3" - could you talk about what work would be required from the design size? I assumed that there would be very little - just adding .mp4 to the list of accepted file formats in the UI.

**Comment by Hanal-code** [comment]
@jodiezhuu  Thanks for working on this. I was able to upload multiple MP4 files to my story map. 


** 1) Files size error message needs to be more specific** 
**CURRENT:** 
<img width="220" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/4baf4559-f8e0-4c6b-b162-0df8810da0b6">

**EXPECTED:**
`{file name} cannot be added because the file is too large. 
`

**Reference:**
file uploader error message 


**2) Hover state of Upload Media button: the button doesn't follow the current pattern.
CURRENT:** Add Media button 
<img width="378" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/bfbacf47-f9fa-4a3a-a264-5be7a37880af">


**EXPECTED** 
Dark blue(#00344D) button 

**References:** 'Save Draft' button 
<img width="226" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/2c665f0c-7d19-46dd-9f21-2f9f653ef18d">

**Comment by Hanal-code** [comment]
@jodiezhuu Fixes have been verified. Thank you!

**Comment by DerekCaelin** [comment]
This is good to be translated and pushed to production.
