### ISSUE TITLE
Editing a site

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#32]
## User Story

- As a user with permissions to edit a site, I can make changes to a site's metadata, including:
  - name
  - ~latitude/longitude~
  - privacy
  - project membership
- As a user with permissions to edit a site, I can initiate the process of editing a site from a variety of places, including:
  - home screen map view
  - My Sites list view
  - individual project views
-  As a user with permissions to edit a site, I can make changes to a site's metadata whenever I am either online or offline

## Definitions

If I have permissions to **edit a Site**, I am one of:
- a manager of a project to which a site belongs
- a manager of the site

```[tasklist]
### Frontend
- [ ] https://github.com/techmatters/terraso-product/issues/117
- [ ] https://github.com/techmatters/terraso-client-shared/issues/17
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/155
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/535
```

```[tasklist]
### Backend
- [ ] https://github.com/techmatters/terraso-backend/issues/401
```

## Acceptance criteria

- I can edit any site that I have manager access to
- I cannot edit the name of a site to be the same as any other site I belong to.
- If I move a site into a project that I don't own, I will no longer own that site.
- If I edit a site while I'm offline, the app should upload those changes to the Terraso server when I'm next online
- If I'm an authenticated user, all site edits that I make should result in a corresponding audit log entry.
- If I try to enter illegal characters into the site's metadata, I should see the appropriate error messages.

[Creating a site](https://docs.google.com/document/d/1vxITdvD9EOjOa92BG7iaSyv55iWZpNCKPDlJOh4sb2Q/edit#)

**Comment by CourtneyLee333** [comment]
@ltseng Do we have any details about changing a site's lat/long? IIRC there was a brief discussion about how this might impact other things (I don't know what) and that we should use a warning message of some sort. I don't see anything in the referenced spec.

**Comment by ltseng** [comment]
It will change the initial predictions returned by the Soil ID algorithm, which will also necessitate retaking data in many cases. We could try to detect if the changed coordinates are merely meters away from the original coordinates and allow a small change like that to go through without any warning, but I'm more inclined at this point, for the sake of simplicity, to just outright ban editing of coordinates and focusing on the less-important metadata like a site's name and privacy, at least until we have the basic functionality working and understand the data inputs better.

@david-code @shrouxm @JeancarloBarrios @paulschreiber how do you feel about this?

**Comment by shrouxm** [comment]
@ltseng either not letting users edit or always let users edit with no additional UX would be about equally simple. some scenarios:
- user wants to move site a small distance: we don't really think of distance at a very high resolution anyway so this is kind of a meaningless action
- user wants to move a site with no data inputs: changing the coords would be an easier way to do this than deleting & recreating the site w the same title, but it's a small UX improvement
- user wants to move a site with data inputs: this only makes sense as an action if someone accidentally input measurements to a site that they took at a different location, which is a bit niche but i would be shocked if it never happened at all and would be quite frustrating to have to manually copy over

it seems pretty difficult for a user to screw themselves over by editing the lat/lng since the old info is preserved in the log & they can just change it back, so i would tend towards being permissive, but i don't feel strongly if you wanna stick with making it un-editable for now

**Comment by ltseng** [comment]
@david-code can you check to see if there are any outstanding tasks around connecting these screens to the backend?

**Comment by ltseng** [comment]
Most of this testing was accomplished during testing of projects, not to mention minimizing the set of things that can be edited for a site.
