### ISSUE TITLE
Design UI for Land Use input

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#377]
This one is straightforward, no wireframe needed. 

[Land tab final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2274%3A18885&mode=design&t=pcwP7cODPGQcFNfG-1)

**Comment by CourtneyLee333** [comment]
Waiting for stakeholder answers to my questions.

**Comment by CourtneyLee333** [comment]
@ltseng Ready for your review. I've changed the screen title from Land Use to Grazing; do you know if there is a particular reason for historically calling Land Use? Is this something we need to run by the stakeholders?

**Comment by ltseng** [comment]
That's a good question, especially since once you click into the Land Use/Land Cover data input in the current app, the title of the second tab is "Grazing" instead of "Land Use." It might be worth running this by Laura/Jeff via email in that thread we have going with them. The most I can come up with is that perhaps grazing is a primarily agricultural term, which doesn't encompass wildlife? But that wouldn't explain why they use Grazing at all.

**Comment by ltseng** [comment]
Otherwise, looks fine!

**Comment by CourtneyLee333** [comment]
I have a screen shot of the "Land" tab in the synthesis notes, which has my suggested verbiage. If we don't get answers in that doc before next meeting I'll bring it up then.

**Comment by CourtneyLee333** [comment]
Prepared for stakeholder meeting.

**Comment by CourtneyLee333** [comment]
@ltseng I have updated the final design per stakeholder feedback.

**Comment by ltseng** [comment]
This matches the feedback we received, to the best of my recollection. Great job!
