### ISSUE TITLE
Plan work to June

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#600]
- [x] clarify everyone's issues for April
- [x] ID user stories, tag and add issues
- [x] Review Capri design remove, add issues that are post launc
- [x] Review slim
- [x] Review bug list, revise according to our [Bug Reporting Guidelines](https://docs.google.com/document/d/1VMgjeLc9zBm7gYuuj7IKmaWXWr8F2uskvadyQWQX9Io/edit#heading=h.ifpkgmo388v)
- [x] Agreement notionally on "what's in, what's out" for the June release
- [x] Explicitly name Capri tasks, add criteria, size.
- [x] Tag all issues with Capri label
- [x] Add testing tasks to each user story
- [x] Add acceptance criteria to each user story

**Comment by DerekCaelin** [comment]
Need to capture what is getting removed from Capri so we can add it into a later enhancement...

**Comment by DerekCaelin** [comment]
Decide: what priority are help sheets and popovers for implemented sections.

**Comment by CourtneyLee333** [comment]
@DerekCaelin one of the things that comes to mind for me is our order of operations after the June launch. Will we get the Global Soil ID out at Capri level, or work on fuller features for US Soil ID? 

Perhaps since BLM crews will already be out in the field during the summer, we should get the Capri global app out and then we can push new features to both as we go down the road?

**Comment by CourtneyLee333** [comment]
Update to say my plan for May includes:
- Existing tickets in the sprint. 
- Lots of QA. 
- Work on User Personas as a low priority task when time is available. 
- Be flexible and ready to respond to Capri needs as they arise. 

Additional planning for May and June are TBD based on the still unfolding roadmap.
