### ISSUE TITLE
Review Help Content for Location Dashboard

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#619]
```[tasklist]
### Tasks
- [x] Review the location dashboard language [in this document](https://docs.google.com/document/d/1qRvfXfjKkoKAXl3jGeDwlRMXw3rYbvJc5ciY06Ehbqw/edit#heading=h.p50cud3q3sni)
```

**Comment by hamriclr** [comment]
No changes needed

**Comment by CourtneyLee333** [comment]
@DerekCaelin Just noting that the document referenced here is one paragraph in Soil ID screen of the temporary location dashboard. The title of this issue is misleading, and it looks like has implications that it shouldn't. I think we have another issue for the main dashboard screen for a site that is still in Laura's review, after which I will apply the relevant text to the temporary site dashboard.

**Comment by DerekCaelin** [comment]
OK - please review this issue as appropriate.
