### ISSUE TITLE
QA for Location Dashboard (Temporary, Site)

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#721]
Use tests: https://docs.google.com/spreadsheets/d/1oARlVfKmtyr5s2elEL8j9SqxX6vDgOeAB8trcRR1IOA/edit?gid=2004954072#gid=2004954072

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I reviewed the dashboard [with these test cases ](https://docs.google.com/spreadsheets/d/1oARlVfKmtyr5s2elEL8j9SqxX6vDgOeAB8trcRR1IOA/edit?gid=2004954072#gid=2004954072) and it looks OK. I notice:
- the data privacy info button does not show up in project sites 
- the radio button for picking site privacy (unaffiliated site) is stacked vertically whereas the design calls for a horizontal array.

**Comment by CourtneyLee333** [comment]
"the data privacy info button does not show up in project sites" - this is expected behavior. Privacy is controlled at the project level, so we are only displaying the privacy setting on the affiliated site dashboard, not offering the control. 

"the radio button for picking site privacy (unaffiliated site) is stacked vertically" - that's ok. I had hoped for a horizontal alignment, but it was extra effort to implement. And for the sake of consistent components we should probably keep all radio buttons vertical.
