### ISSUE TITLE
Adapt HubSpot templates for deletion experience

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#745]
Develop a "request received" and "account has been deleted" template in HubSpot.

**Comment by CourtneyLee333** [comment]
I don't believe we need the "request received" email. I've included that info in the app instead.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 @paulschreiber 

I've created a template [here](https://app.hubspot.com/templates/9151742/edit/21193052)

![Image](https://github.com/techmatters/terraso-product/assets/10799815/ebe51fe9-1af0-437b-85b4-98cad98c3b4a)

**Comment by CourtneyLee333** [comment]
This looks fine to me. Some email clients won't display inline images, but I don't think there is anything we can do about that. 

Is there a similar template for deleting a Terraso account? I'm wondering because it looks like this template was created 3 years ago and just modified. It might be helpful to name this "LandPKS Account Deletion". I think going forward it's going to be helpful to delineate LandPKS and Terraso things in Hubspot.

**Comment by DerekCaelin** [comment]
There isn't a method to delete Terraso accounts yet! Although it seems like the process we are going through will be helpful for that in the future. I will rename the template.
