### ISSUE TITLE
Research documentation experiences powered by WordPress

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#820]
Research documentation experiences that will deliver the Soil ID documentation experience displayed in [Courtney's IA document.](https://app.mural.co/t/techmatters9109/m/techmatters9109/1709825491386/d591551193671747aeddf5e5b220cf8a58695c87?sender=u3faecbd439cadb255c696741)

## Acceptance Criteria
- [x] review various sites documentation experiences
- [x] Recommend model site
- [ ] Ideal - recommend wordpress plugin to deliver the experience

**Comment by CourtneyLee333** [comment]
Two sites that seem relevant to me are ARcGIS and Ecobot:


![Image](https://github.com/techmatters/terraso-product/assets/8915145/8dfe127d-61cf-459e-a9b3-6e8e06106dcc)



![Image](https://github.com/techmatters/terraso-product/assets/8915145/1681253a-9d2c-4516-8277-8102d52ee605)



![Image](https://github.com/techmatters/terraso-product/assets/8915145/42563802-68cd-4d77-bd38-e23aa00a8e95)

**Comment by CourtneyLee333** [comment]
They both start with a block style layout to welcome the user to the help section. Once into the help documentation, I'm partial to ArcGIS's use of the table of contents style layout, so that the user can quickly scan through all the chapters and topics to target what they're looking for. 

I like Ecobot's CTAs for contacting support.

**Comment by CourtneyLee333** [comment]
I've done some experimenting and and believe we can make this work fine with GeneratePress.
