### ISSUE TITLE
QA for Project Management Experience - Courtney

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#852]
Perform QA on Project management using the [tests in this folder](https://drive.google.com/drive/folders/1irQu6c9J896RSFYNzTcNIFhs474BJgme).

- Create
- Edit 
- Delete

(Not included: site transfers)

**Comment by CourtneyLee333** [comment]
Create and edit project errors: When I enter more than 72 char for description, the Save button is disabled but I have no way of knowing why. [https://tech-matters.slack.com/archives/C06BQTCAUJF/p1717767604883889](https://www.google.com/url?q=https://tech-matters.slack.com/archives/C06BQTCAUJF/p1717767604883889&sa=D&source=editors&ust=1717771418885829&usg=AOvVaw3lJq2DomVQZ5oFW38MjwDr)
This is also an issue for Project Name. Should be fixed with the [task of implementing the proper component](https://github.com/techmatters/terraso-mobile-client/issues/1318).

**Comment by DerekCaelin** [comment]
I've logged these issues! Thanks, closing this task.
