### ISSUE TITLE
Develop Google form - QA signin experience, provide permissions, inital map view

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#957]
Test cases for sign: [Test](https://docs.google.com/spreadsheets/d/1AnjoVZ1zqu0J7apdyzAcJNBZccgrRqacJo_XgJJZh6o/edit?gid=2004954072#gid=2004954072)

[The Google form](https://docs.google.com/forms/d/1edSmHNFyutWN6_ncm_155UgzZURgA_lxC5yexqEqqLk/edit)

```[tasklist]
### Tasks
- [x] Derek writes
- [x] Courtney reviews
```

**Comment by CourtneyLee333** [comment]
Do we want people to be testing prod or beta now? According to my convo with Paul yesterday, the general flow should be to QA beta before pushing to prod, and expect that it will be identical when pushed to prod. We'll need to make sure the most up to date one is pushed to their group if they're in beta, and that the instructions for updating are still accurate. 

This should not still be relevant: Please note that there are bugs to be aware of:
 After signing in, there will be a brief delay before you see the home screen map.

Do we need to add instructions on how to delete and reinstall the app? 

I changed "interstitial" to "Welcome" for people who don't know what that is. 

The permissions dialog doesn't display until after you've signed in, so the order of that needs to be changed in the form. 

Test Case 1 needs to include the right conditionals on the "Did you receive the expected outcome?" answer; yes would lead to the next test case, no would lead to the bug report. 

It looks like section 4 - the bug report for welcome and location - isn't complete. I think you meant to allow for uploads where the radio buttons are?

It seems the tile of "Test Case 2 - Sign In with Google" should remove the Google part, since they should sign in with whatever they want. Or do you mean to add test cases for each of the sign-in options? I'd add the instructions to record the number of seconds at the top of that section so they know to pay attention to it while performing the action. I don't understand what "(using the current build)" means. Do you mean to add a bug section for the test case?

**Comment by DerekCaelin** [comment]
Ugh. I linked to the wrong form above. I have updated the link. The full form is the one I put in my own drive: 
https://docs.google.com/forms/d/1edSmHNFyutWN6_ncm_155UgzZURgA_lxC5yexqEqqLk/edit

I addressed the issues that you mention. Would you glance over the new form?

> Do we want people to be testing prod or beta now?
Agreed with you and Paul; In general, we will be releasing features in development on beta before pushing to production. In this specific case, sign-in is already on prod, so it doesn't matter which branch people are on.

> The permissions dialog doesn't display until after you've signed in, so the order of that needs to be changed in the form.
Is that the desired behavior? iOS shows permissions on the Welcome screen, Android waits to see the map. Which is the desired flow?

**Comment by CourtneyLee333** [comment]
The desired flow is to request permissions after you sign in. 

I changed "interstitial" to "Welcome" for people who don't know what that is.

In section 4, I think "(using the current build)" is confusing. We've already asked them to make sure to have the most recent version. Do you mean something different?

I changed a couple of the conditionals that weren't quite right.

**Comment by DerekCaelin** [comment]
I've made the changes. We'll send this out once the relevant bugs with permissions are addressed.
