### ISSUE TITLE
Design data layers 

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#98]
How should they look over topographic (raster and vector) and satellite maps?

```[tasklist]
- [ ] Wireframes approved
- [ ] Final Desing approved
```
[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)
[LandPKS Wireframes and Prototype](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype?t=hiT0127wb8Tey06i-1) - Transfer Existing Sites, Transfer Existing Sites dialog

**Comment by CourtneyLee333** [comment]
@ltseng Do we have details about this in a spec? Are the data layers supposed to be semi-transparent? Is there some specific design work I'm supposed to do with the data layers? I realize I wrote the note above, but I've lost the context.

**Comment by ltseng** [comment]
Overall, I would like:
- a design for where users would interact with the home screen map in order to turn data layers on and off
- For soil maps: a color gradient design/legend for how we display the most likely soils within a given area.
  - [NRCS's web soil survey](https://websoilsurvey.nrcs.usda.gov/app/WebSoilSurvey.aspx) is clunky to use, but looks like this:
![image](https://github.com/techmatters/terraso-product/assets/2730009/bfb0a0c2-c56d-45dd-8f39-09b74915dec4)   
  - [HWSD](https://hqfao.maps.arcgis.com/apps/dashboards/ab43f3f516364e77998f0c0abf655571) is only good at zoomed-out views, but is a bit more accessible
![image](https://github.com/techmatters/terraso-product/assets/2730009/86155c4c-d116-44ce-bc4c-b8a3d99efaae)

**Comment by ltseng** [comment]
This is actually not as easily digestible as, say, a topographic or satellite map, now that I'm thinking about it a bit more...let's pull Laura into a discussion at some point this month.

**Comment by CourtneyLee333** [comment]
@ltseng Is there actually anything for me to do here? I think we've decided to go with the existing yellow and black polygon borders for now.

**Comment by ltseng** [comment]
Nope, I think you're done here 😁
